version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: test.log
    maxBytes: 1024
    backupCount: 3
    encoding: utf-8
  mail:
    class: logging.handlers.SMTPHandler
    mailhost: mail01.etzone.net
    fromaddr: no-reply@ehsn.com.tw
    toaddrs: 
      - rocky.wang@ehsn.com.tw
    subject: Error on OB DataSync  
    formatter: simple
    level: ERROR
    
loggers:
  simpleLogger:
    level: DEBUG
    handlers: [console, file, mail]
    propagate: yes
    
root:
  level: DEBUG
  handlers: [console, file, mail]