version: 1
formatters:
  simple:
    format: '%(asctime)s %(name)s - %(levelname)s - %(message)s'
    
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: simple
    filename: test.log
    when: S
    interval: 1
    backupCount: 3
    encoding: utf-8
  mail:
    class: logging.handlers.ThreadedTlsSMTPHandler
    mailhost: ('smtp.gmail.com', 587)
    fromaddr: rockywang101@gmail.com
    toaddrs: 
      - rocky.wang@ehsn.com.tw
    subject: Error Occur
    credentials: ('rockywang101@gmail.com', 'xxx') 
    formatter: simple
    level: ERROR
    
root:
  level: DEBUG
  handlers: [console, file, mail]